# Generated by Django 2.1.1 on 2018-11-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0003_auto_20181118_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='empresa',
            field=models.CharField(max_length=64, null=True, verbose_name='Empresa'),
        ),
    ]
