# Generated by Django 2.1.1 on 2018-12-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0004_auto_20181118_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='blog_imagenes')),
                ('imagen_mobile', models.ImageField(upload_to='blog_imagenes_mobile')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='frontpage',
            new_name='in_catalog',
        ),
    ]
