# Generated by Django 2.0.3 on 2018-10-10 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64, verbose_name='Nombre')),
                ('porcentaje', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje')),
                ('tipo', models.CharField(choices=[('1', 'Habilidad'), ('2', 'Experiencia')], default='1', max_length=1, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Experiencia',
                'verbose_name_plural': 'Experiencias',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=64, verbose_name='Autor')),
                ('nombre', models.CharField(max_length=64, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=128, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=32, verbose_name='Teléfono')),
                ('email', models.CharField(max_length=64, verbose_name='Correo Electrónico')),
                ('webpage', models.CharField(max_length=64, verbose_name='Página Web')),
                ('puesto', models.CharField(max_length=64, verbose_name='Puesto de Trabajo')),
                ('imagen', models.ImageField(upload_to='perfil_imagenes', verbose_name='Imagen')),
                ('cv', models.FileField(blank=True, max_length=32768, null=True, upload_to='perfil_cv', verbose_name='Resumen')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfil',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=64, verbose_name='Título')),
                ('descripcion', models.TextField(max_length=256, verbose_name='Descripción')),
                ('tags', models.CharField(blank=True, help_text='Separe las etiquetas con una coma: tag1,tag2,tag3...', max_length=64, null=True, verbose_name='Etiquetas')),
                ('url', models.URLField(max_length=128, verbose_name='URL')),
                ('imagen', models.ImageField(upload_to='proyectos_imagenes')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='Reconocimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=64, verbose_name='Título')),
                ('descripcion', models.TextField(max_length=512, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Reconocimiento',
                'verbose_name_plural': 'Reconocimientos',
            },
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64, verbose_name='Nombre')),
                ('puesto', models.CharField(max_length=64, verbose_name='Puesto de Trabajo')),
                ('empresa', models.CharField(max_length=64, verbose_name='Empresa')),
                ('comentario', models.TextField(max_length=512, verbose_name='Comentario')),
                ('imagen', models.ImageField(upload_to='referencias_imagenes')),
            ],
            options={
                'verbose_name': 'Referencia',
                'verbose_name_plural': 'Referencias',
            },
        ),
    ]
