# Generated by Django 2.1.1 on 2018-10-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='empresa',
            field=models.CharField(default=None, max_length=64, verbose_name='Título'),
            preserve_default=False,
        ),
    ]
